begin;
select set_config('request.jwt.claim.sub',(select id::text from public.profiles where ruolo='admin' and attivo limit 1),true);
set local role authenticated;
do $$
declare st uuid; sid uuid; eid uuid; completed uuid; req uuid:=gen_random_uuid(); payload jsonb; res jsonb; contact uuid; iid uuid; itemids uuid[]; before_count integer; blocked boolean:=false; worker uuid;
begin
 insert into stores(nome) values('V198 TEST ROLLBACK') returning id into st;
 select id into worker from profiles where attivo and ruolo='dipendente' limit 1;
 payload=jsonb_build_object('day','2099-01-01','members',jsonb_build_array(auth.uid()),'stores',jsonb_build_array(st),'extras','[]'::jsonb);
 res=overgreen_admin_v198(req,'schedule_create',payload);sid=(res->>'id')::uuid;
 assert overgreen_admin_v198(req,'schedule_create',payload)=res,'idempotency';
 assert (select count(*) from schedules where id=sid)=1,'one schedule';
 begin perform overgreen_admin_v198(req,'schedule_create',payload||'{"day":"2099-01-02"}'); exception when others then blocked=true; end;
 assert blocked,'request cannot be reused with different data';
 select count(*) into before_count from schedules;
 begin perform overgreen_admin_v198(gen_random_uuid(),'schedule_create',payload||jsonb_build_object('stores',jsonb_build_array(gen_random_uuid()))); exception when foreign_key_violation then null; end;
 assert (select count(*) from schedules)=before_count,'failed creation rolls back';
 res=overgreen_admin_v198(gen_random_uuid(),'contact',jsonb_build_object('contact',jsonb_build_object('nome','V198 contact','client_type','intesa'),'stores',jsonb_build_array(st)));
 contact=(res->>'id')::uuid;
 assert (select client_type='intesa' from work_contacts where id=contact),'contact fields';
 assert exists(select 1 from contact_stores where contact_id=contact and store_id=st),'contact links';
 insert into extras(store_id,titolo,schedule_id,giorno_intervento,stato) values(st,'open',sid,'2099-01-01','programmato') returning id into eid;
 insert into extra_workers values(eid,auth.uid());
 insert into extras(store_id,titolo,schedule_id,giorno_intervento,stato) values(st,'closed',sid,'2099-01-01','completato') returning id into completed;
 perform overgreen_admin_v198(gen_random_uuid(),'schedule_date',jsonb_build_object('id',sid,'day','2099-01-02'));
 assert (select giorno_intervento='2099-01-01' from extras where id=completed),'completed date protected';
 assert (select giorno_intervento='2099-01-02' from extras where id=eid),'open date moved';
 perform overgreen_admin_v198(gen_random_uuid(),'schedule_team',jsonb_build_object('id',sid,'members',jsonb_build_array(worker)));
 assert exists(select 1 from extra_workers where extra_id=eid and profile_id=worker),'extra team synchronized';
 assert not exists(select 1 from extra_workers where extra_id=eid and profile_id=auth.uid()),'old extra assignment removed';
 eid=gen_random_uuid();
 res=overgreen_admin_v198(gen_random_uuid(),'extra_create',jsonb_build_object('extra',jsonb_build_object('id',eid,'store_id',st,'titolo','V198 extra','giorno_intervento','2099-01-02'),'members',jsonb_build_array(worker),'work_items',jsonb_build_array(jsonb_build_object('titolo','work')),'attachment',jsonb_build_object('id',gen_random_uuid(),'storage_path','extra/'||eid||'/request.pdf','nome_file','request.pdf','dimensione_bytes',1)));
 assert exists(select 1 from extras where id=eid and schedule_id=sid),'extra reuses team schedule';
 assert exists(select 1 from extra_work_items where extra_id=eid),'work rows saved';
 select array_agg(id) into itemids from schedule_items where schedule_id=sid;
 insert into schedule_items(schedule_id,tipo,store_id,stato) values(sid,'ordinario',st,'completato') returning id into iid;
 itemids=array_append(itemids,iid);
 insert into interventions(store_id,data_intervento,data_fine,stato,multi_day_open,schedule_item_ids) values(st,'2099-01-01','2099-01-03','convalidato',false,itemids) returning id into iid;
 perform overgreen_admin_v198(gen_random_uuid(),'delete_intervention',jsonb_build_object('id',iid));
 assert not exists(select 1 from interventions where id=iid),'intervention deleted';
 assert not exists(select 1 from schedule_items where id=any(itemids) and stato<>'da_fare'),'all linked items reopened';
end $$;
rollback;
select 'PASS: transactional contacts, idempotency, rollback, date history, team sync, extra creation, multiday deletion; fixtures rolled back' as result;
