const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const src=fs.readFileSync(__dirname+'/../app.js','utf8');
const header='EUROSPIN SPESA INTELLIGENTE Richiesta intervento n. 123456 del 08/09/2026 Punto Vendita: SPESA INTELLIGENTE S.p.A. BEINASCO Tel. 011123456 Fax 011999999 ';
function context(){
 const nodes=new Map(),$=id=>{if(!nodes.has(id))nodes.set(id,{value:'',files:[],classList:{add(){},remove(){}},addEventListener(){}});return nodes.get(id)};
 const c={console,$,retroExtraCreateContext:null,stores:[],syncExtraClosureOptions(){},syncOrdinaryIncludedCreateUi(){},syncExtraNumberLabel(){},renderExtraStoreOptions(){},syncExtraDestinationUi(){},checkDuplicateTargetField(){},clearDuplicateTargetWarning(){},findStoreFromPdf:()=>null,fmt:s=>s};vm.createContext(c);
 vm.runInContext(src.slice(src.indexOf('function pdfDateToIso'),src.indexOf('function normalizeMatchText')),c);
 vm.runInContext(src.slice(src.indexOf('let extraPdfReadVersion='),src.indexOf('function workItemsForExtra')),c);return c;
}
test('Eurospin greeting request excludes contacts, invoicing and signature',()=>{const c=context(),p=c.parseKnownExtraPdf(header+'Buongiorno, si richiede di effettuare la potatura della siepe. Rimuovere anche i rami secchi. Cordiali saluti Ufficio tecnico La fattura deve essere intestata a SPESA INTELLIGENTE');assert.equal(p.client,'eurospin');assert.equal(p.number,'123456');assert.equal(p.title,'effettuare la potatura della siepe.');assert.equal(p.description,'si richiede di effettuare la potatura della siepe. Rimuovere anche i rami secchi.');assert.equal(p.category,'verde');});
test('subject and labelled request both remain in description',()=>{const c=context(),p=c.parseEurospinPdf(header+'Oggetto: Lavaggio parcheggio Descrizione intervento: Lavaggio del piano interrato e rimozione delle macchie. La fattura deve riportare il target.');assert.equal(p.title,'Lavaggio parcheggio');assert.equal(p.description,'Lavaggio parcheggio\nLavaggio del piano interrato e rimozione delle macchie.');assert.equal(p.category,'pulizie');});
test('alternate body label and free-form request without greeting',()=>{const c=context();assert.equal(c.parseEurospinPdf(header+'Lavori da eseguire: Riparazione del cancello.').title,'Riparazione del cancello.');assert.equal(c.parseEurospinPdf(header+'Si richiede un sopralluogo per una perdita. Grazie.').description,'Si richiede un sopralluogo per una perdita.');});
test('missing request never uses metadata; ambiguous category stays unset',()=>{const c=context(),p=c.parseEurospinPdf(header+'La fattura deve indicare il numero target.');assert.equal(p.title,null);assert.equal(p.description,null);assert.equal(c.parseEurospinPdf(header+'Buongiorno, sfalcio erba e pulizia parcheggio.').category,null);});
test('long request keeps full description and produces a short title',()=>{const c=context(),body='Lavaggio delle superfici '+('del parcheggio e delle rampe '.repeat(12)),p=c.parseEurospinPdf(header+'Descrizione richiesta: '+body);assert(p.title.length<=120);assert.equal(p.description,body.trim());});
test('Intesa parser still reads its original title and details',()=>{const c=context(),p=c.parseKnownExtraPdf('Intesa Sanpaolo TICKET 1 7 8 4 3 3 1 Città: Torino Indirizzo: Via Roma 1 Richiesto da: Tecnico Descrizione intervento: Pulizia ingresso Dettaglio della richiesta: Lavaggio pavimento Guasto: ordinario Apertura ticket di guasto il 08/09/2026');assert.equal(p.number,'1784331');assert.equal(p.title,'Pulizia ingresso');assert.equal(p.description,'Lavaggio pavimento');});
test('actual autofill writes Eurospin title and description into the form',async()=>{const c=context(),file={};c.$('extraPdf').files=[file];c.readPdfText=async()=>header+'Buongiorno, potatura siepe. La fattura deve riportare il target.';await c.autoFillExtraFromPdf(file);assert.equal(c.$('extraTitle').value,'potatura siepe.');assert.equal(c.$('extraDescription').value,'potatura siepe.');assert.match(c.$('extraPdfAutoReadStatus').textContent,/titolo · descrizione/);});
test('out-of-order PDF reads and manual typing cannot be overwritten',async()=>{const c=context(),first={},second={};let resolveFirst,resolveSecond;c.readPdfText=f=>new Promise(r=>{if(f===first)resolveFirst=r;else resolveSecond=r});c.$('extraPdf').files=[first];const a=c.autoFillExtraFromPdf(first);c.$('extraPdf').files=[second];const b=c.autoFillExtraFromPdf(second);c.$('extraTitle').value='Titolo scritto da me';resolveSecond(header+'Buongiorno, Lavaggio parcheggio.');await b;resolveFirst(header+'Buongiorno, Potatura siepe.');await a;assert.equal(c.$('extraTitle').value,'Titolo scritto da me');assert.equal(c.$('extraDescription').value,'Lavaggio parcheggio.');});
