const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),{randomUUID}=require('crypto');
const src=fs.readFileSync(__dirname+'/../app.js','utf8');
function block(start,end){const a=src.indexOf(start),b=src.indexOf(end,a+start.length);assert(a>=0&&b>a);return src.slice(a,b)}
function ctx(extra={}){const nodes=new Map();const c={console,crypto:{randomUUID},sessionStorage:{data:new Map(),getItem(k){return this.data.get(k)||null},setItem(k,v){this.data.set(k,v)},removeItem(k){this.data.delete(k)}},alert(){},$:id=>{if(!nodes.has(id))nodes.set(id,{value:'all',dataset:{},querySelectorAll:()=>[],textContent:'Salva'});return nodes.get(id)},...extra};vm.createContext(c);return c}
(async()=>{
 const c=ctx();vm.runInContext(block('async function withFormBusy','const cfg'),c); // following declarations harmless if present
 let sends=0;await Promise.all([c.withFormBusy('f',async()=>{sends++;await Promise.resolve()}),c.withFormBusy('f',async()=>{sends++})]);assert.equal(sends,1);
 console.log('PASS concurrent form submit runs once');
 const ids=[];let fail=true;const a=ctx({sb:{rpc:async(n,args)=>{ids.push(args.p_request_id);if(fail){fail=false;return {error:new Error('response lost')}}return {data:{id:'saved'}}}}});vm.runInContext(block('async function adminOperation','async function withFormBusy'),a);await assert.rejects(a.adminOperation('schedule_create',{day:'x'}));await a.adminOperation('schedule_create',{day:'x'});assert.equal(ids[0],ids[1]);console.log('PASS uncertain response reuses request ID');
 const d=ctx({attachments:[],profiles:[],stores:[],extraWorkItems:[],extraWorkItemPhotos:[],extraWorkItemNotes:[],scheduleActivities:[],scheduleActivityPhotos:[],dailyReportData:()=>({ordinary:[{id:'1',note:'old'}],extra:[]})});vm.runInContext(block('function dailyReportPdfKey','async function getDailyReportPdf'),d);const key=d.dailyReportPdfKey();d.dailyReportData=()=>({ordinary:[{id:'1',note:'new'}],extra:[]});assert.notEqual(key,d.dailyReportPdfKey());const noteKey=d.dailyReportPdfKey();d.attachments.push({id:'photo1',storage_path:'first'});const photoKey=d.dailyReportPdfKey();d.attachments[0].storage_path='replacement';assert.notEqual(photoKey,d.dailyReportPdfKey());console.log('PASS PDF note and same-count photo invalidation');
 const e=ctx({extras:[{id:'1',numero_target:'123',client_type:'eurospin'}],clientType:r=>r.client_type});vm.runInContext(block('function findExistingExtraByTarget','function clearDuplicateTargetWarning'),e);assert.equal(e.findExistingExtraByTarget('123',null,'intesa'),null);assert.equal(e.findExistingExtraByTarget('123',null,'eurospin').id,'1');console.log('PASS ticket uniqueness scoped to customer');
 const f=ctx({scheduleItems:[{store_id:'st',schedule_id:'s',stato:'annullato'}],schedules:[{id:'s'}],effectiveScheduleState:r=>r.stato});vm.runInContext(src.split('\n').find(l=>l.startsWith('function isStoreProgrammed')),f);assert.equal(f.isStoreProgrammed('st'),false);console.log('PASS cancelled work excluded');
 const removed=[];const g=ctx({attachments:[{id:'old',extra_id:'e',tipo:'pdf_richiesta',storage_path:'old'}],saveExtraUpload:async()=>{throw new Error('upload failed')},sb:{storage:{from:()=>({remove:async p=>{removed.push(p);return {}}})},from:()=>{throw new Error('old metadata must remain')}}});vm.runInContext(block('async function replaceExtraAttachment','let extraGroupOpenState'),g);await assert.rejects(g.replaceExtraAttachment('e','pdf_richiesta',{}));assert.equal(removed.length,0);assert.equal(g.attachments.length,1);console.log('PASS failed replacement preserves original');
 const zip=ctx({window:{JSZip:true},eurospinPackageSelectedCategories:()=>['verde','pulizie'],renderEurospinPackageCheck(){},eurospinPackageState:{groups:{verde:[{check:{ready:true},e:{}}],pulizie:[{check:{ready:true},e:{}}]}},eurospinPackageMonthLabel:()=> 'SETTEMBRE',buildEurospinCategoryZip:async(cat,rows)=>{assert.equal(cat,'both');assert.equal(rows.length,2);return {size:100}},toast(){}});zip.$('eurospinPackageMonth').value='2026-09';zip.$('eurospinPackageSummary').insertAdjacentHTML=()=>{};zip.$('packageProgress').remove=()=>{};vm.runInContext(block('async function generateEurospinMonthlyPackages','function downloadEurospinPackage'),zip);await zip.generateEurospinMonthlyPackages();assert.deepEqual(Object.keys(zip.eurospinPackageState.downloads),['both']);console.log('PASS both categories produce one ZIP');
 const route=ctx();vm.runInContext(block('function routeAddressForStore','function formatTravelMinutes'),route);assert.equal(route.routeAddressForStore({nome:'FOSSANO'}),'FOSSANO, Italia');assert.equal(route.routeAddressForStore({}), '');assert.equal(route.routeAddressForExtra({nome_esterno:'FOSSANO'},null),'FOSSANO, Italia');console.log('PASS incomplete address never resolves to country alone');
 console.log('8 regression groups passed');
})().catch(e=>{console.error(e);process.exitCode=1});
