const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto'),{IDBFactory}=require('fake-indexeddb');
const Sync=require('../photo-sync.js');
function fixture(t,overrides={}){
 let time=100000,who={profileId:'worker',callerId:'worker'};
 const store=Sync.storage(new IDBFactory()),submits=[],uploads=[],events=[],objects=new Map(),receipts=new Map(),interventions=new Map();
 const api={
  async submit(row,photos){submits.push(row.id);if(!interventions.has(row.id))interventions.set(row.id,{intervention:{id:'i-'+row.id,foto_attese:photos.length}});return interventions.get(row.id)},
  async register(job){return {storage_path:'interventi/'+job.interventionId+'/'+job.id+'-'+job.fileName}},
  async event(job,stage,error){events.push({id:job.id,stage,error})},
  async upload(job){uploads.push(job.id);objects.set(job.id,job.file)},
  async finalize(job){if(!objects.has(job.id))return {received:false};receipts.set(job.id,true);return {received:true,attachment:{id:job.id}}},...overrides
 };
 const create=()=>{const q=Sync.create({store,actor:()=>who,now:()=>time,api});t.after(()=>q.stop());return q};
 return {q:create(),create,store,api,submits,uploads,events,objects,receipts,interventions,advance:ms=>time+=ms,switchActor:value=>who=value};
}
function attempt(count=2){const files=Array.from({length:count},(_,i)=>new File(['photo-'+i],'foto-'+i+'.jpg',{type:'image/jpeg'}));return {args:{p_request_id:randomUUID(),p_store_id:'site',p_photo_count:count,p_actor_id:'worker'},photoIds:files.map(()=>randomUUID()),files}}
test('all photos and the closure survive a reload before the first network call',async t=>{const h=fixture(t),a=attempt();await h.q.prepare(a);assert.equal(h.submits.length,0);assert.equal((await h.store.all('photos')).length,2);h.q.stop();const resumed=h.create();await resumed.run();assert.equal(h.interventions.size,1);assert.equal(h.receipts.size,2);assert.equal((await resumed.snapshot()).jobs.length,0)});
test('an aborted local transaction cannot leave a closure or half a photo set',async t=>{const h=fixture(t),base=h.store.tx;h.store.tx=async(names,mode,run)=>base(names,mode,tx=>{const r=run(tx);if(mode==='readwrite'&&names.includes('submissions'))tx.abort();return r});await assert.rejects(h.q.prepare(attempt()));assert.equal((await h.store.all('submissions')).length,0);assert.equal((await h.store.all('photos')).length,0);assert.equal(h.submits.length,0)});
test('unreadable/empty camera data never reaches the closure API',async t=>{const h=fixture(t),a=attempt(1);a.files[0]=new File([],'empty.jpg',{type:'image/jpeg'});await assert.rejects(h.q.prepare(a),/vuota/);await h.q.run();assert.equal(h.submits.length,0)});
test('lost closure response replays the same request after reload',async t=>{const h=fixture(t),submit=h.api.submit;let fail=true;h.api.submit=async(...args)=>{const r=await submit(...args);if(fail){fail=false;throw Error('response lost')}return r};const a=attempt();await h.q.prepare(a);await h.q.run();h.q.stop();assert.equal(h.interventions.size,1);await h.create().resume();assert.deepEqual(h.submits,[a.args.p_request_id,a.args.p_request_id]);assert.equal(h.interventions.size,1);assert.equal(h.receipts.size,2)});
test('failed local binding after server closure is recoverable with the original request',async t=>{const h=fixture(t),a=attempt();await h.q.prepare(a);const base=h.store.tx;let fail=true;h.store.tx=(names,mode,fn)=>{if(fail&&mode==='readwrite'&&names.includes('submissions')&&names.includes('jobs')){fail=false;return Promise.reject(Error('disk interrupted'))}return base(names,mode,fn)};await h.q.run();assert.equal((await h.q.getSubmission(a.args.p_request_id)).result,null);await h.q.resume();assert.equal(h.interventions.size,1);assert.equal(h.receipts.size,2)});
test('temporary errors retry beyond three failures, while new photos still proceed',async t=>{const h=fixture(t),a=attempt(1),b=attempt(1),upload=h.api.upload;h.api.upload=async j=>{if(j.id===a.photoIds[0]&&h.events.filter(e=>e.id===j.id&&e.stage==='retrying').length<4)throw Object.assign(Error('temporary network error'),{status:503});return upload(j)};await h.q.prepare(a);await h.q.run();await h.q.prepare(b);await h.q.run();assert(h.receipts.has(b.photoIds[0]));for(let n=0;n<5;n++){h.advance(310000);await h.q.run()}assert(h.receipts.has(a.photoIds[0]));assert.equal((await h.q.snapshot()).jobs.length,0)});
test('permission errors pause and retain the file until explicit retry',async t=>{const h=fixture(t),upload=h.api.upload;h.api.upload=async()=>{throw Object.assign(Error('denied'),{status:403})};await h.q.prepare(attempt(1));await h.q.run();assert((await h.q.snapshot()).jobs[0].blocked);h.advance(999999);await h.q.run();assert.equal(h.events.filter(e=>e.stage==='uploading').length,1);h.api.upload=upload;await h.q.retry();assert.equal(h.receipts.size,1)});
test('lost upload response is reconciled without uploading a second copy',async t=>{const h=fixture(t),upload=h.api.upload;h.api.upload=async j=>{await upload(j);throw Error('upload response lost')};await h.q.prepare(attempt(1));await h.q.run();await h.q.resume();assert.equal(h.uploads.length,1);assert.equal(h.receipts.size,1);assert.equal((await h.q.snapshot()).jobs.length,0)});
test('lost finalization response keeps the backup and verifies on retry',async t=>{const h=fixture(t),finalize=h.api.finalize;let fail=true;h.api.finalize=async j=>{const r=await finalize(j);if(r.received&&fail){fail=false;throw Error('receipt lost')}return r};await h.q.prepare(attempt(1));await h.q.run();assert.equal((await h.q.snapshot()).jobs.length,1);assert.equal((await h.store.all('photos'))[0].uploadedAt,null);await h.q.resume();assert.equal(h.uploads.length,1);assert.equal((await h.q.snapshot()).jobs.length,0)});
test('expired unsent recovery copies survive; only acknowledged copies expire',async t=>{const h=fixture(t),a=attempt(1);await h.q.prepare(a);h.advance(8*86400000);await h.q.cleanup();assert.equal((await h.store.all('photos')).length,1);await h.q.run();h.advance(8*86400000);await h.q.cleanup();assert.equal((await h.store.all('photos')).length,0);assert.equal((await h.store.all('receipts')).length,1)});
test('old jobs with three errors are imported and sent after force approval',async t=>{const h=fixture(t),row={id:randomUUID(),interventionId:'already-approved',actorProfileId:'worker',file:new File(['old'],'old.jpg',{type:'image/jpeg'}),fileName:'old.jpg',retries:3};await h.q.restore([row]);await h.q.run();assert.equal(h.receipts.size,1);await h.q.restore([row]);assert.equal((await h.q.snapshot()).jobs.length,0)});
test('another account cannot view or send an existing local queue',async t=>{const h=fixture(t);await h.q.prepare(attempt());h.switchActor({profileId:'other',callerId:'other'});assert.equal((await h.q.snapshot()).jobs.length,0);await h.q.run();assert.equal(h.submits.length,0);assert.equal(h.uploads.length,0);h.switchActor({profileId:'worker',callerId:'worker'});await h.q.run();assert.equal(h.receipts.size,2)});
test('concurrent triggers share one worker and a single upload per photo',async t=>{const h=fixture(t);await h.q.prepare(attempt());await Promise.all([h.q.run(),h.q.run(),h.q.run()]);assert.equal(h.submits.length,1);assert.equal(h.uploads.length,2)});
test('new recovery files can attach to an already-approved intervention',async t=>{const h=fixture(t);await h.q.attach('approved',[new File(['late'],'late.jpg',{type:'image/jpeg'})],[randomUUID()]);await h.q.run();assert.equal(h.submits.length,0);assert.equal(h.receipts.size,1)});
test('restoring a Blob backup preserves its original file name and bytes',async t=>{const h=fixture(t),id=randomUUID();await h.q.attach('approved',[new File(['unique-photo'],'camera-original.jpg',{type:'image/jpeg'})],[id]);const backup=await h.store.get('photos',id);await h.store.tx(['jobs'],'readwrite',t=>t.objectStore('jobs').delete(id));await h.q.restore([backup]);const restored=(await h.q.snapshot()).jobs[0];assert.equal(restored.fileName,'camera-original.jpg');assert.equal(await restored.file.text(),'unique-photo');await h.q.run();assert.equal(h.receipts.size,1)});
